#################################################################
## Binary Sensor
#################################################################

# Ping WAN (www.google.com)
- platform: ping
  name: Internet Status
  host: google.com
  scan_interval: 30
# washing_machine_running:
#   friendly_name: "Washing Machine Running"
#   delay_off:
#     minutes: 5
#   value_template: "{{ states('sensor.washing_machine_switch_wattage')| float > 0 }}"
