homeassistant:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # http:
  #   base_url: example.duckdns.org:8123

  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  allowlist_external_dirs:
    - /config

  media_dirs:
    media: /media

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24 #=> Local network
        - 10.0.8.0/24 #=> VPN network

  customize: !include customize.yaml

# RESTful API
# https://www.home-assistant.io/integrations/api
api:

# Discover some devices automatically
discovery:
  ignore:
    - harmony
    - homekit

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Logger
# https://home-assistant.io/components/logger/
logger:
  default: error

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_project_id
  # # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  # subscriber_id: !secret nest_subscriber_id

# Component for storing details in database
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 3
  exclude:
    domains:
      - calendar
      - automation
      - updater
      - ping
      - remote
      - automation
      - sun
      - weather
      - media_player
    entities:
      - sensor.time
      - sensor.moon
      - sensor.next_sunrise
      - sensor.next_sunset
      - sensor.last_boot
      - sensor.hdhr3_cc_signal_quality
      - sensor.hdhr3_cc_signal_strength
      - sensor.automation_count
      - sensor.binary_sensor_count
      - sensor.sensor_count
      - sensor.scene_count
      - sensor.script_count
      - sensor.switch_count
      - sensor.lights_count
      - sensor.upcoming_holiday_date
      - sensor.upcoming_holiday
      - sensor.trash_pickup_date
      - sensor.trash_pickup_day
      - sensor.curbside_recycling_date
      - sensor.curbside_recycling_day
      - sensor.new_york_knicks_game_countdown
      - sensor.new_york_giants_game_countdown
      - sensor.new_york_yankees_game_countdown
      # - sensor.wow_raid_countdown

# lovelace:
#   mode: storage

#   resources:
#     # https://github.com/thomasloven/lovelace-card-tools
#     - url: /local/card-tools.js
#       type: js

#     # https://github.com/custom-cards/secondaryinfo-entity-row
#     - url: /local/secondaryinfo-entity-row.js
#       type: module

#     # https://github.com/custom-cards/upcoming-media-card
#     - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
#       type: js

media_player:
  # Emby
  # https://www.home-assistant.io/integrations/emby/
  # - platform: emby
  #   host: !secret nas_host_name
  #   api_key: !secret emby_api_key

  # # Yamaha AV Receiver
  # # https://www.home-assistant.io/components/yamaha/
  # - platform: yamaha
  #   host: !secret av_receiver_host_name

  # Android TV
  # https://www.home-assistant.io/integrations/androidtv#adb-setup
  - platform: androidtv
    name: Basement Shield
    host: !secret basement_nvidia_shield_host_name
    apps:
      com.silicondust.view: HDHomeRun
      tv.emby.embyatv: Emby
      pandora.android.atv: Pandora
      com.plexapp.android: Plex
      com.amazon.amazonvideo.livingroom: Prime Video
      com.netflix.ninja: Netflix
      com.google.android.youtube.tv: YouTube

# TP-Link
# https://www.home-assistant.io/components/tplink/
# tplink:
#   discovery: false
#   switch:
#     #- host: !secret mini_christmas_tree_host_name
#     #- host: !secret christmas_tree_host_name
#     - host: !secret plant_grow_lights_host_name
#     - host: !secret cable_modem_switch_host_name

# UPS
# https://www.home-assistant.io/components/apcupsd/
apcupsd:
  host: !secret nas_host_name

# Google Calendar
# https://www.home-assistant.io/components/calendar.google/
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: true

# SpeedTest
# https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:

# Proxmox VE
proxmoxve:
  - host: !secret proxmox_ip_address
    username: !secret proxmox_username
    password: !secret proxmox_password
    verify_ssl: false
    realm: pve
    nodes:
      - node: ommiepve
        vms:
          - 103
          - 104
        containers:
          - 102

# Includes
group: !include groups.yaml
automation: !include automations.yaml
light: !include light_group.yaml
script: !include scripts.yaml
zone: !include zones.yaml
input_select: !include input_select.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
scene: !include scene.yaml
switch: !include switch.yaml
