homeassistant:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # http:
  #   base_url: example.duckdns.org:8123

  # Name of the location where Home Assistant is running
  # name: Home
  # # Location required to calculate the time the sun rises and sets
  # latitude: !secret home_latitude
  # longitude: !secret home_longitude

  # # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: !secret home_elevation

  # currency: USD

  # # metric for Metric, imperial for Imperial
  # unit_system: imperial
  # # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: America/New_York

  allowlist_external_dirs:
    - /config

  media_dirs:
    media: /media

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24 #=> Local network
        - 10.0.8.0/24 #=> VPN network

  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret ngnix_proxy_manager   # Nginx-PM IP
    - 172.17.0.1    # Nginx-PM Docker0 IP
    - 172.30.232.1  # Home Assistant Docker0 IP
    - 172.30.32.1   # Hassio IP

# RESTful API
# https://www.home-assistant.io/integrations/api
api:

# Discover some devices automatically
discovery:
  ignore:
    - harmony
    - homekit

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# # Enables the frontend
# frontend:
#   themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Logger
# https://home-assistant.io/components/logger/
logger:
  default: error

# Wake on LAN
wake_on_lan:

# Component for storing details in database
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 3
  exclude:
    domains:
      - calendar
      - automation
      - updater
      - ping
      - remote
      - automation
      - sun
      - weather
      - media_player
    entities:
      - sensor.time
      - sensor.moon
      - sensor.next_sunrise
      - sensor.next_sunset
      - sensor.last_boot
      - sensor.hdhr3_cc_signal_quality
      - sensor.hdhr3_cc_signal_strength
      - sensor.automation_count
      - sensor.binary_sensor_count
      - sensor.sensor_count
      - sensor.scene_count
      - sensor.script_count
      - sensor.switch_count
      - sensor.lights_count
      - sensor.upcoming_holiday_date
      - sensor.upcoming_holiday
      - sensor.trash_pickup_date
      - sensor.trash_pickup_day
      - sensor.curbside_recycling_date
      - sensor.curbside_recycling_day
      - sensor.new_york_knicks_game_countdown
      - sensor.new_york_giants_game_countdown
      - sensor.new_york_yankees_game_countdown
      # - sensor.wow_raid_countdown

# Proxmox VE
proxmoxve:
  - host: !secret proxmox_ip_address
    username: !secret proxmox_username
    password: !secret proxmox_password
    verify_ssl: false
    realm: pve
    nodes:
      - node: ommiepve
        vms:
          - 100
          - 103
          - 104
          - 106
        containers:
          - 102
          # - 105

# Includes
# group: !include groups.yaml
automation: !include automations.yaml
# light: !include light_group.yaml
script: !include scripts.yaml
zone: !include zones.yaml
input_select: !include input_select.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
scene: !include scene.yaml
switch: !include switch.yaml
